name: qr_scanner_app
description: A comprehensive QR Code Scanner Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mobile_scanner: ^5.0.0 # or latest version
  permission_handler: ^11.0.0
  url_launcher: ^6.2.0
  image_picker: ^1.0.0
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Optional: Add custom fonts or assets here
  # assets:
  #   - images/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
